stages:
    - build
    - test
    - package

variables:
    IMAGE_NAME: 'log-service'

build:
    stage: build
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    script:
        - podman --version
        - podman build -f log/Dockerfile -t ${IMAGE_NAME}:latest .
        - podman save -o log-service.tar ${IMAGE_NAME}:latest
    artifacts:
        name: logservice-artifact
        paths:
            - log-service.tar
            - build

test:
    stage: test
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    script:
        - podman load -i log-service.tar
        - podman run --name test-container ${IMAGE_NAME}:latest npx tsx --test --test-force-exit --test-reporter=junit --test-reporter-destination=test-report.xml log/logService.test.ts || TEST_EXIT=$?
        - podman cp test-container:/app/test-report.xml ./test-report.xml
        - podman rm test-container
        - exit ${TEST_EXIT:-0}
    artifacts:
        name: logservice-test-report
        when: always
        reports:
            junit: test-report.xml

package:
    stage: package
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    variables:
        PACKAGE_NAME: 'package:${CI_COMMIT_SHORT_SHA}'
    script:
        - ls -la
        - |
            cat <<EOF > Dockerfile
            FROM alpine:latest
            WORKDIR /app
            COPY log-service.tar /app/log-service.tar
            CMD ["ls", "-la", "/app"]
            EOF
        - podman build -t "$PACKAGE_NAME" .
        - mkdir -p package-artifact
        - podman save "$PACKAGE_NAME" | gzip > package-artifact/devops-package.tar.gz
    artifacts:
        name: package-artifact
        paths:
            - package-artifact/devops-package.tar.gz
        when: always
