stages:
    - build
    - test

variables:
    IMAGE_NAME: 'log-service'

build:
    stage: build
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    script:
        - podman --version
        - podman build -f log/Dockerfile -t ${IMAGE_NAME}:latest .
        - podman save -o log-service.tar ${IMAGE_NAME}:latest
    artifacts:
        name: logservice-artifact
        paths:
            - log-service.tar

test:
    stage: test
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    script:
        - podman load -i log-service.tar
        - podman run --name test-container ${IMAGE_NAME}:latest npx tsx --test --test-force-exit --test-reporter=junit --test-reporter-destination=test-report.xml log/logService.test.ts || TEST_EXIT=$?
        - podman cp test-container:/app/test-report.xml ./test-report.xml
        - podman rm test-container
        - exit ${TEST_EXIT:-0}
    artifacts:
        - name: logservice-test-report
          when: always
          reports:
              junit: test-report.xml
