stages:
    - build

variables:
    IMAGE_NAME: 'log-service'

build:
    stage: build
    tags:
        - SE140-2026
    image:
        name: quay.io/podman/stable
        pull_policy: always
    script:
        - podman --version
        - podman build -f log/Dockerfile -t ${IMAGE_NAME}:latest .
        - podman save -o log-service.tar ${IMAGE_NAME}:latest
    artifacts:
        name: logservice-artifact
        paths:
            - log-service.tar
